name: Deploy CRA to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./mp2/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./mp2

      - name: Build site
        run: npm run build
        working-directory: ./mp2

      # SPA fallback so BrowserRouter works on refresh/deep links
      - name: SPA fallback
        run: cp mp2/build/index.html mp2/build/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: mp2/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
